### ISSUE TITLE
Android: Mute/Unmute has no effect when a stream with audio track is opened repeatedly.

### ISSUE THREAD

**Issue by basyskom-bmeier** [flutter-webrtc/flutter-webrtc#1186]
**Describe the bug**

- I want to mute/umute an audio track using the `enabled` property of the respective `MediaStreamTrack` object.
- This works as expected when the stream is opened for the first time. I can toggle mute/unmute repeatedly and it works as expected.
- When the stream is closed and opened a second time, it usually does not work, I can hear the audio playing even when the stream gets muted/disabled.
- I added callbacks for `onMute` and `onUnmute` and I can see those are triggered as expected.
- Since this works on ios, I have a suspicion that it's a bug in the Android part of flutter-webrtc. 
- However, I can't completely rule out the possibility that I'm doing something wrong either, so I'd appreciate any further advice or questions.

**Expected behavior**

- Even if a stream is opened and closed several times in a row, mute/unmute should work.

**Platform information**

* **Flutter version**:

Linux/Android Setup:
```
[✓] Flutter (Channel stable, 3.3.9, on Ubuntu 20.04.5 LTS 5.15.0-53-generic, locale de_DE.UTF-8)
    • Flutter version 3.3.9 on channel stable at /home/_/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (8 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/bmei/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

```

Macos/iOS Setup:
```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.5 21G72 darwin-x64, locale de-DE)
  • Flutter version 3.3.1 on channel stable at /Users/_/tools/flutter
  • Upstream repository https://github.com/flutter/flutter.git
  • Framework revision 4f9d92fbbd (vor 3 Monaten), 2022-09-06 17:54:53 -0700
  • Engine revision 3efdf03e73
  • Dart version 2.18.0
  • DevTools version 2.15.0

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
  • Xcode at /Applications/Xcode.app/Contents/Developer
  • Build 14A400
  • CocoaPods version 1.11.3
```

* **Plugin version**:

```
flutter_webrtc:
  dependency: "direct main"
  description:
    name: flutter_webrtc
    url: "https://pub.dartlang.org"
  source: hosted
  version: "0.9.17"

webrtc_interface:
  dependency: transitive
  description:
    name: webrtc_interface
    url: "https://pub.dartlang.org"
  source: hosted
  version: "1.0.10"

dart_webrtc:
  dependency: transitive
  description:
    name: dart_webrtc
    url: "https://pub.dartlang.org"
  source: hosted
  version: "1.0.11"
```

* **OS**:
- Android: 11, 13
- iOS: 16.1

* **OS version**:

- Ubuntu 20.04.5 LTS
- macos Monterey 12.5
