### ISSUE TITLE
Linux Snap - Fatal error in adm_helpers

### ISSUE THREAD

**Issue by lyskouski** [flutter-webrtc/flutter-webrtc#1477]
**Describe the bug**

By packaging Flutter project into the snap-build for a distribution, its evaluation is failed with the next error:
```
# Fatal error in: ../../media/engine/adm_helpers.cc, line 39
# last system error: 88
# Check failed: 0 == adm->Init() (0 vs. -1)
# Failed to initialize the ADM
```

**To Reproduce**

It can be used a sample project with installed dependency.

`snapcraft.yaml`
```yaml
name: sample
base: core22
version: 1.0.0+1

grade: stable
confinement: strict

apps:
  sample:
    command: sample
    plugs: [home, desktop, desktop-legacy, network, network-bind, opengl, x11]
    extensions: [gnome]

parts:
  app-finance:
    source: .
    plugin: flutter
    build-packages: [libgtk-3-dev, ninja-build]
    stage-packages: [libgtk-3-0]
    flutter-target: lib/main.dart
```

Build (for Ubuntu):
```console
sudo snap install snapcraft --classic
snapcraft --verbose
sudo snap install sample.snap --dangerous
```

**Expected behavior**

Application is started without exceptions

**Platform information**

* **Flutter version**: Flutter (Channel stable, 3.13.8, on KDE neon 5.27 6.2.0-35-generic, locale en_US.UTF-8)
    • Flutter version 3.13.8 on channel stable at /home/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c4930c4ac, 2023-10-18 10:57:55 -0500
    • Engine revision 767d8c75e8
    • Dart version 3.1.4
    • DevTools version 2.25.0

* **Plugin version**: 0.9.42+hotfix.1
* **OS**:  Desktop
* **OS version**: KDE neon 5.27
