### ISSUE TITLE
Flathub distribution:  `GLIBCXX_3.4.32' not found

### ISSUE THREAD

**Issue by lyskouski** [flutter-webrtc/flutter-webrtc#1480]
Hello, would rely on your assistance.

`flutter-webrtc` works for Linux in general (from flutter build), from Snap, but not as Flathub package.

**Describe the bug**

```console
fingrom: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /app/Fingrom/lib/libflutter_webrtc_plugin.so)
```

**To Reproduce**
```console
sudo apt install flatpak-builder
flatpak-builder build-dir com.tercad.fingrom.yml --force-clean
flatpak-builder --user --install --force-clean build-dir com.tercad.fingrom.yml
flatpak run com.tercad.fingrom
```

File: com.tercad.fingrom.yml
```yaml
app-id: com.tercad.fingrom
runtime: org.freedesktop.Platform
runtime-version: "23.08"
sdk: org.freedesktop.Sdk
command: fingrom
separate-locales: false
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --socket=pulseaudio
  - --share=network
  - --share=ipc
  - --device=dri
modules:
  - name: Fingrom
    buildsystem: simple
    only-arches:
      - x86_64
    build-commands:
      - mkdir -p Fingrom
      - tar -xf fingrom_Linux.tar.gz -C Fingrom
      - cp -r Fingrom /app/Fingrom
      - chmod +x /app/Fingrom/fingrom
      - mkdir -p /app/bin
      - ln -s /app/Fingrom/fingrom /app/bin/fingrom
# Not helping
#      - mkdir -p /app/lib
#      - ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /app/lib/libstdc++.so.6
      - install -Dm644 /app/Fingrom/com.tercad.fingrom.svg /app/share/icons/hicolor/scalable/apps/com.tercad.fingrom.svg
      - install -Dm644 /app/Fingrom/com.tercad.fingrom.desktop /app/share/applications/com.tercad.fingrom.desktop
      - install -Dm644 com.tercad.fingrom.metainfo.xml /app/share/appdata/com.tercad.fingrom.metainfo.xml
    sources:
      - type: file
        url: https://github.com/lyskouski/app-finance/releases/download/v5.0.1/fingrom_Linux.tar.gz
        # sha256sum fingrom_Linux.tar.gz
        sha256: ce16ac7c02914f9fa845b8da1d5f2656a4d9e23d33c1c73c78c2af5d22931a1f
#      - type: file
#        path: com.tercad.fingrom.metainfo.xml
```

**Expected behavior**

Started without errors.

**Platform information**

* **Flutter version**: 3.13.9
* **Plugin version**: 0.9.42+hotfix.1
* **OS**: Desktop (Linux)
* **OS version**: KDE neon 5.27
