### ISSUE TITLE
MediaRecorder implementation for iOS

### ISSUE THREAD

**Issue by rostopira** [flutter-webrtc/flutter-webrtc#47]
I can barely read Objective-C code, so help wanted)

**Comment by aryzhov** [comment]
Could you outline the needed functionality and volume of work?

**Comment by rostopira** [comment]
For basic functionality we need capturing, encoding and muxing of video/audio track
Current dart api here: https://github.com/cloudwebrtc/flutter-webrtc/blob/master/lib/media_recorder.dart
Android implementation here: https://github.com/cloudwebrtc/flutter-webrtc/pull/46 
It's originally based on original implementation of https://webrtc.googlesource.com/src/+/master/sdk/android/api/org/webrtc/VideoFileRenderer.java
Just added encoding, muxing and recording of local audio (unfortunately impossible to record any other AudioTrack due to current WebRTC implementation)
However, I've didn't find any hints for encoding or even writing to file in ios part of that repo

**Comment by rostopira** [comment]
It's almost there!
If somebody wants to test it:
```yaml
  flutter_webrtc:
    git:
      url: https://github.com/cloudwebrtc/flutter-webrtc
      ref: ios_recorder
```
